### ISSUE TITLE
"Stockfish path provided is not valid"

### ISSUE THREAD

**Issue by mlovescoding** [PanagiotisIatrou/chess-auto-bot#40]
When I download stockfish, select it in the GUI, and start it, I get this error. On the terminal it says,

Exception ignored in: <function Stockfish.__del__ at 0x0000015273DDE5C0>
Traceback (most recent call last):
  File "C:\Users\Gaming Laptop\chess-auto-bot-main\venv\Lib\site-packages\stockfish\models.py", line 777, in __del__
    self.send_quit_command()
  File "C:\Users\Gaming Laptop\chess-auto-bot-main\venv\Lib\site-packages\stockfish\models.py", line 770, in send_quit_command
    if self._stockfish.poll() is None:
       ^^^^^^^^^^^^^^^
AttributeError: 'Stockfish' object has no attribute '_stockfish'

I read all of the past issues and none of then help my problem.

**Comment by PanagiotisIatrou** [comment]
Hello, @mlovescoding. Did you select the stockfish executable on the GUI? If so, what is your python version?
