### ISSUE TITLE
OSError: [WinError 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by YashaRektr** [PanagiotisIatrou/chess-auto-bot#74]
D:\Games\Chess\chess-auto-bot>venv\Scripts\python.exe src\gui.py
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "D:\Games\Chess\chess-auto-bot\src\gui.py", line 465, in on_open_browser_button_listener
    self.chrome = webdriver.Chrome(
  File "D:\Games\Chess\chess-auto-bot\venv\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 84, in __init__
    super().__init__(
  File "D:\Games\Chess\chess-auto-bot\venv\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 101, in __init__
    self.service.start()
  File "D:\Games\Chess\chess-auto-bot\venv\lib\site-packages\selenium\webdriver\common\service.py", line 96, in start
    self._start_process(self._path)
  File "D:\Games\Chess\chess-auto-bot\venv\lib\site-packages\selenium\webdriver\common\service.py", line 197, in _start_process
    self.process = subprocess.Popen(
  File "C:\Program Files\Python310\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python310\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 193] %1 is not a valid Win32 application

**Comment by fishball0077** [comment]
same error

**Comment by Codealuxz** [comment]
same

**Comment by PanagiotisIatrou** [comment]
Hello @YashaRektr! Thanks for pointing it out. I think I fixed it with commit 7fdf2c73a1d34bc2b8fd5c65ab41f9bf280be738 by upgrading from PyQt5 to PyQt6. Can you check if it works?
